--liquibase formatted sql

--changeset atul:create-employee-table
--comment: Initial schema for employee management
CREATE TABLE employee (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(50) NOT NULL,
                          email VARCHAR(100) NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--rollback DROP TABLE employee;

--changeset atul:add-employee-email-unique-constraint
--comment: Enforce uniqueness on employee email addresses
ALTER TABLE employee ADD CONSTRAINT uk_employee_email UNIQUE (email);

--rollback ALTER TABLE employee DROP CONSTRAINT uk_employee_email;

--changeset atul:add-employee-username-index
--comment: Add index on username for faster lookups
CREATE INDEX idx_employee_username ON employee(username);

--rollback DROP INDEX idx_employee_username;
